name: ActionBarTimer
version: 1.0
main: Main.Main
api-version: 1.17
authors: [ getQueryString, Jovaniwu ]
description: Timer plugin by getQueryString for Jovaniwu
website: https://www.youtube.com/c/mrdudecrafthd

commands:
  timer:
    permission: timer.command